-- =================================================================
-- Patch: Split Actions to Separate Table
-- Reason: Refactor JSON actions to Relational Table
-- Date: 2025-12-30
-- =================================================================

-- 1. Create New Table
CREATE TABLE stage_actions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    stage_config_id BIGINT,
    action_label VARCHAR(255),
    button_style VARCHAR(50),
    target_type VARCHAR(50),
    target_stage VARCHAR(255),
    post_action_status VARCHAR(255),
    FOREIGN KEY (stage_config_id) REFERENCES stage_config(id) ON DELETE CASCADE
);

-- 2. Rename Old Column (Preserve Data for Migration)
ALTER TABLE stage_config ALTER COLUMN allowed_actions RENAME TO allowed_actions_legacy;
